---

ntp_driftfile: /var/lib/ntp/drift
ntp_server: [0.uk.pool.ntp.org, 1.uk.pool.ntp.org, 2.uk.pool.ntp.org, 3.uk.pool.ntp.org]
ntp_restrict:
  - "restrict default nomodify notrap nopeer noquery"
  - "restrict 127.0.0.1"

ntp_crypto: no
ntp_includefile: "/etc/ntp/crypto/pw"
ntp_keys: "/etc/ntp/keys"
ntp_trustedkey: "4 8 42"
ntp_requestkey: "8"
ntp_controlkey: no
ntp_statistics: no
ntp_broadcast: no 
ntp_broadcastclient: no         
ntp_multicastclient: no

