---
yum_user: nginx
yum_pkgs:
  - createrepo
  - nginx
  - yum-utils
yum_source:
  - name: Baseos
    description: CentOS-10 Base
  - name: AppStream
    description: CentOS-10 AppStream
  - name: epel
    description: CentOS-10 EPEL
  - name: extras-common
    description: CentOS-10 extras  

...
