---
yum_user: nginx
yum_pkgs:
  - createrepo
  - nginx
  - yum-utils
yum_source:
  - name: baseos
    description: CentOS-10 Base
  - name: appstream
    description: CentOS-10 AppStream
  - name: epel
    description: CentOS-10 EPEL
  - name: extras-common
    description: CentOS-10 extras  

...
