---

galaxy_info:
  role_name: chrony
  author: "Paul Burgess"
  company: enenet
  license: BSD
  min_ansible_version: 1.4
  platforms:
   - name: EL
     versions:
#      - 7
#      - 8
       - 9
#  galaxy_tags:
#    - system
#    - time
#    - ntp
#    - chromy
#    - date
#categories:
#   - development
...