---
yum_repos:
  - filename: centos-base.repo
    baseurl: 192.168.1.117/base
    gpgkey: ///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    gpgcheck: 0
    enabled: 1
  - filename: centos-updates.repo
    baseurl: 192.168.1.117/updates
    gpgkey: ///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    gpgcheck: 0
    enabled: 1
  - filename: epel.repo
    baseurl: 192.168.1.117/epel
    gpgkey: ///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    gpgcheck: 0
    enabled: 1
...
