---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_distribution }}.yml"

- name: Install the required  packages in Redhat derivatives
  yum: name={{ yum_pkgs }} state=installed
  when: ansible_os_family == 'CentOS'

- name: Create a backup confiuration directory
  ansible.builtin.file:
    path: "{{ backup_dir }}"
    state: directory
    mode: '0755'

- name: Get the list of files to move
  find:
    paths: "{{ configuration_dir }}"
    patterns: "*"
    recurse: no
  register: configuration_files

- name: Move files
  command: mv {{ item.path }} {{ backup_dir }}
  with_items: "{{ configuration_files.files }}"



#  stat: path={{ yum_backup }}
#  register: yum_stat

#- name: Move yum configuration to backup
#  command: mv {{ item }} {{ yum_backup }}
#  with_fileglob:
#     - "/etc/yum.repos.d/*"
  #when: yum_stat.stat.exists

  #command: mv {{ yum_dir }} {{ yum_backup }}
  #args:
  #  creates: "{{ yum_dir }}"  

 #     "{{ items }}"
 #   dest: "/etc/yum.repos.backup.d/" 
 #   backup: yes
 # with_fileglob:
 #   - "/etc/yum.repos.d/*"

- name: create templates for repository files
  ansible.builtin.template:
    src: local.repo.j2
    dest: "{{ configuration_dir }}{{ item.filename }}" 
    owner: root
    mode: 644
#    backup: true
  with_items: "{{ yum_repos }}"
  
  #debug:
  #  msg: "{{ item.filename }}"
  #loop: "{{ yum_repos }}"

  #debug:
  #  msg: "{{ item.values() }}"
  #loop: "{{ yum_repos }}"

  #debug:
  #  msg: "{{ item }}"
  #loop: "{{ yum_repos }}"

  #debug:
  #  msg: "{{ yum_repos | type_debug }}"
  
  #debug:
  #  msg: "{{ item | dict2items }}"
  #loop: "{{ yum_repos }}"
  #with_dict: "{{ yum_repos }}"
  #template:
  #  src: local.repo.j2
  #  dest: /etc/yum.repos.d

#- name: Create the templates for local repo files in current configuration directory
#  template: src=local.repo.j2 dest="/etc/yum.repos.d/{{items.iteritem().next()}}"
#  with_items: yum_repos

#- name: Rename files to remove ".j2" extension
#  template: src={{ item }} dest=/tmp/{{ item | basename | regex_replace('.j2','') }}
#   with_fileglob:
#  - /etc/yum.repos.d/*.j2
#  notify: 
#    - reload yum 
...
