- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the required  packages in Redhat derivatives
  yum: name={{ item }} state=installed
  with_items: '{{ ntp_pkgs }}'
  notify: restart ntp
  when: ansible_os_family == 'RedHat'

- name: Install the required packages in Debian derivatives
  apt: name={{ item }} state=installed update_cache=yes
  with_items: '{{ ntp_pkgs }}'
  environment: env
  notify: restart ntp
  when: ansible_os_family == 'Debian'

- name: Install the required packages in Slackware 
  command: slackpkg install '{{ ntp_pkgs }}'
  notify: restart Slackware ntp
  when: ansible_os_family == 'Slackware'

- name: Copy the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
        