---
# yum_server: http://192.168.0.111/repos/10
# name: {{item}}
baseurl: http://192.168.0.111
# enabled: 1
yum_repos:
  - filename: centos-base.repo
    name: base
    baseurl: $baseurl/BaseOS
    gpgkey: file://etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    gpgcheck: 0
    enabled: 1
  - filename: centos-updates.repo
    name: updates
    baseurl: $baseurl/updates
    gpgkey: file://etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    gpgcheck: 0
    enabled: 1
  - filename: epel.repo
    name: epel
    baseurl: $baseurl/epel
    gpgkey: file://etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    gpgcheck: 0
    enabled: 1
  - filename: extras.repo
    name: extras
    baseurl: $baseurl/extras
    gpgkey: file://etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    gpgcheck: 0
    enabled: 1
  #- filename: centos-ansible-29.repo
  #  name: centos-ansible-29
  #  baseurl: $baseurl/centos-ansible-29
  #  gpgkey: file://etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
  #  gpgcheck: 0
  #  enabled: 1 
  #- filename: epel-testing.repo
  #  name: epel-testing
  #  baseurl: $baseurl/centos-ansible-29
  #  gpgkey: file://etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
  #  gpgcheck: 0
  #  enabled: 1  
...
